routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('', 'HomeController@index')->name('home');
Route::resource('clientes', 'ClientesController')->middleware('auth');
Route::resource('produto', 'ProdutoController')->middleware('auth');
Route::resource('tamanhoProduto', 'TamanhoProdutoController')->middleware('auth');
Route::resource('fornecedor', 'FornecedorController')->middleware('auth');
Route::resource('unidade', 'UnidadeController')->middleware('auth');
Route::resource('estoque', 'EstoqueController')->middleware('auth');
Route::resource('compra', 'CompraController')->middleware('auth');
Route::resource('compraRest', 'CompraRestController')->middleware('auth');
Route::get('/produtoApi/nextid', 'ProdutoController@getNextID')->name('produtoNextID')->middleware('auth');
Route::post('/compraRest/{id}', 'CompraRestController@update')->middleware('auth');

app/produto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class produto extends Model
{
    public static $imagePath = 'arquivos/produtos/';
    public $path = 'arquivos/produtos/';
    protected $fillable = ['nome','imagem','codigo','precoVenda','precoCusto','descricao'];

    public function estoque(){
        return $this->hasMany(estoque::class);
    }

    public function getSelectFormatAttribute()
    {
        return $this->codigo . " - " . $this->nome;
    }

    public function getQuantidadeEstoqueAttribute(){
        $somatorio = 0;
        foreach ($this->estoque as $estoque) {
            $somatorio += $estoque->quantidade;
        }
        return $somatorio;
    }

    public static function getAllActives(){
        return produto::where('ativo', 1)->get();
    }

    public static function getAllForSelect(){
        return produto::getAllActives()->pluck('select_format', 'id');
    }

    public static function getNextID()
    {
        $statement = DB::select("show table status like 'produtos'");
        return response()->json(['id' => $statement[0]->Auto_increment]);
    }
}

app/Http/Controllers/ProdutoController.php
<?php

namespace App\Http\Controllers;

use App\produto;
use App\Repositories\Interfaces\IProdutoRepository;
use Illuminate\Http\Request;

class ProdutoController extends Controller
{
    protected $iProdutoRepository;

    public function __construct(IProdutoRepository $iProdutoRepository)
    {
        $this->iProdutoRepository = $iProdutoRepository;
    }
    public function index()
    {
        $produtos = Produto::all();
        return view('produto.index', compact('produtos', $produtos));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("produto.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->iProdutoRepository->addProduto($request);
        return redirect('produto');
    }

    /**
     * Display the specified resource.Rua
     *
     * @param  \App\Produto  $produtos
     * @return \Illuminate\Http\Response
     */
    public function show(Produto $produto)
    {
        return view('produtos.show', compact('produto', $produto));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Produto  $produtos
     * @return \Illuminate\Http\Response
     */
    public function edit(Produto $produto)
    {
        return view('produto.edit', compact('produto', $produto));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  String $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, String $id)
    {
        $this->iProdutoRepository->updateProduto($request, $id);

        $request->session()->flash("message", "Produto modificado com sucesso");

        return redirect('produto');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param String $id
     * @return
     */
    public function destroy(String $id)
    {
        $produto = Produto::findOrFail($id);
        $this->iProdutoRepository->deleteImageAndThumb($produto);
        $produto->delete();
        return redirect('produto')->with("message", "Produto excluido com sucesso");
    }

    public function getNextID(){
        return produto::getNextID();
    }

}

resources/views/produto/create.blade.php
@extends('layouts.blank')

@section('main_container')
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Incluir Produto</h2>
                <ul class="navbar-right panel_toolbox">
                    <li>
                        <a href="{{ URL::previous() }}" class="btn btn-primary btn-xs">
                            <i class="fa fa-arrow-left"></i> Voltar
                        </a>
                    </li>
                </ul>
            <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                {!! Form::open(['route' => 'produto.store','method'=>'POST', 'files' => true]) !!}
                @include('produto.form')
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/produto/edit.blade.php
@extends('layouts.blank')

@section('main_container')
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Alterar Produto</h2>
                <ul class="navbar-right panel_toolbox">
                    <li>
                        <a href="{{ URL::previous() }}" class="btn btn-primary btn-xs">
                            <i class="fa fa-arrow-left"></i> Voltar
                        </a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                    {!! Form::model($produto, ['method' => 'PATCH','route' => ['produto.update', $produto->id], 'files' => true]) !!}
                    @include('produto.form')
                    {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/produto/form.blade.php
<div class="row">

    <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{Form::label('codigo', 'Codigo')}}
                {{ Form::text('codigo', null, array('placeholder' => '','class' => 'form-control')) }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{Form::label('nome', 'Nome')}}
                {{ Form::text('nome', null, array('placeholder' => '','class' => 'form-control')) }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{Form::label('precoVenda', 'Preco Venda')}}
                {{ Form::text('precoVenda', null, array('placeholder' => '','class' => 'form-control')) }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{Form::label('precoCusto', 'Preco Custo')}}
                {{ Form::number('precoCusto', null, array('placeholder' => '','class' => 'form-control')) }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{Form::label('descricao', 'Descricao')}}
                {{ Form::text('descricao', null, array('placeholder' => '','class' => 'form-control')) }}
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <br>
                    @if(isset($produto->imagem))
                        <img class="produto-imagem img-responsive center-block" src="{{url($produto->path . "thumb" .$produto->imagem)}}"><br>
                    @endif
                {{Form::file('imagem', array('placeholder' => '','class' => 'center-margin'))}}

            </div>
        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">
            @if(isset($produto->estoque))
            <table class="table table-hover" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th scope="col">Tamanho</th>
                    <th scope="col">Quantidade</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                    @foreach($produto->estoque as $estoque)
                        <tr>
                            <td scope="row" >{{$estoque->tamanhoProduto->nome}}</td>
                            <td scope="row" >{{$estoque->quantidade}}</td>
                            <td scope="row">
                                <a href="{{ URL::to('estoque/' . $estoque->id . '/edit') }}" class="btn btn-primary btn-xs">
                                    <i class="fa fa-pencil"></i> Ver
                                </a>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
    </div>
</div>
<button type="submit" class="btn btn-primary">Gravar</button>

resources/views/produto/index.blade.php
@extends('layouts.blank')
 
@section('main_container')

        <div class="col-md-12 col-sm-12 col-xs-12">
            @if (Session::has('message'))
                <div class="alert alert-info">{{ Session::get('message') }}</div>
            @endif
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Produtos</h2>
                    <ul class="navbar-right panel_toolbox">
                        <li>
                            <a href="{{Route('produto.create')}}" class="btn btn-primary btn-xs">
                                <i class="fa fa-plus"></i> Inserir
                            </a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Código</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Preço</th>
                            <th scope="col">Estoque</th>
                            <th scope="col" >Ações</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($produtos as $produto)
                            <tr>
                                <td scope="row">{{$produto->id}}</td>
                                <td scope="row">{{$produto->codigo}}</td>
                                <td scope="row">{{$produto->nome}}</td>
                                <td scope="row">{{$produto->precoVenda}}</td>
                                <td scope="row">{{$produto->quantidade_estoque}}</td>
                                <td scope="row">
                                    @component('components.actions', ['entidade' => 'produto', 'id' => $produto->id])
                                    @endcomponent
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>





@endsection